apiVersion: apps/v1
kind: Deployment
metadata:
  name: teethcare-backend
  namespace: staging
spec:
  template:
    spec:
      containers:
      - name: teethcare-backend
        env: 
          - name: DB_TYPE
            value: teethcare-staging
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: sapassword
