apiVersion: apps/v1
kind: Deployment
metadata:
  name: teethcare-backend
spec:
  selector:
    matchLabels:
      app: teethcare-backend
  replicas: 2
  strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
  template:   
    spec:
      containers:
      - name: teethcare-backend
        env: 
          - name: DB_TYPE
            value: teethcare-staging
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: sapassword
