apiVersion: apps/v1
kind: Deployment
metadata:
  name: teethcare-backend
  namespace: prod
spec:
  selector:
    name: teethcare-backend
  template:
    replicas: 2
    spec:
      containers:
      - name: teethcare-backend
        env: 
          - name: DB_TYPE
            value: teethcare-prod
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: sapassword
