apiVersion: apps/v1
kind: Deployment
metadata:
  name: teethcare-backend
spec:
  selector:
    matchLabels:
      app: teethcare-backend
  replicas: 3
  strategy:
      rollingUpdate:
        maxSurge: 1
        maxUnavailable: 1
      type: RollingUpdate
  template:
    spec:
      containers:
      - name: teethcare-backend
        env:
          - name: LOGGING_FILE_PATH
            value: /var/log/teethcare
          - name: LOGGING_FILE_NAME
            value: teethcare-prod.log
          - name: DB_TYPE
            value: teethcare-prod
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: sapassword
      - name: fluentd
        resources:
          limits:
            memory: "300Mi"
            cpu: "100m"
        env: 
        - name: FLUENT_UID
          value: root
        - name: FLUENTD_CONF
          value: fluent.conf
        - name: FLUENTD_OPT
          value: -c /fluentd/etc/fluent.conf
        
        image: globalgames/fluentd-gelf:latest
        volumeMounts:
          - name: applog
            mountPath: /var/log/teethcare/
          - name: fdconf 
            mountPath: /fluentd/etc/
      volumes:
      - name: applog
        emptyDir: {}
      - name: fdconf
        configMap:
          name: fluentd-config
        
          
