resources:
- ../../base
namespace: prod
patchesStrategicMerge:
- deployment.yaml
namePrefix: production-
images:
- name: 553061678476.dkr.ecr.ap-southeast-1.amazonaws.com/backend
  newTag: 0.0.1
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
