resources:
 - ../../base
patchesStrategicMerge:
 - deployment.yaml
namePrefix: production-
namespace: prod
images:
  - name: 553061678476.dkr.ecr.ap-southeast-1.amazonaws.com/backend
    newTag: 1.0.0
