apiVersion: apps/v1
kind: Deployment
metadata:
  name: teethcare-backend
  namespace: qa
  labels:
    app: teethcare-backend
spec:
  selector:
    matchLabels:
      app: teethcare-backend
  template:
    spec:
      containers:
      - name: teethcare-backend
        env: 
          - name: DB_TYPE
            value: teethcare-qa
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: sql-secret
                key: sapassword