# patchesStrategicMerge:
#  - deployment.yaml
namePrefix: qa-
namespace: qa
patchesStrategicMerge:
- deployment.yaml
images:
- name: 553061678476.dkr.ecr.ap-southeast-1.amazonaws.com/backend
  newTag: null-CI-CD
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
